# Generated by Django 4.1 on 2022-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('nr_telefonu', models.CharField(max_length=200)),
                ('informacje_ogolne', models.TextField(verbose_name=2000)),
                ('wyksztalcenie', models.CharField(max_length=200)),
                ('szkola', models.CharField(max_length=200)),
                ('uniwersytet', models.CharField(max_length=200)),
                ('doswiadczenie', models.TextField(max_length=1000)),
                ('umiejetnosci', models.TextField(max_length=1000)),
            ],
        ),
    ]
